### ISSUE TITLE
Where can I find Apollo queries?

### ISSUE THREAD

**Issue by NooBiToo** [strapi/strapi-starter-nuxt-blog#26]
Good afternoon,
I have seen a starter pack before, where requests were separately highlighted in the apollo folder, but in this version I cannot find where the requests to the graphql are located in order to customize the application

**Comment by Mcastres** [comment]
Hey @NooBiToo, this starter is now using the [@nuxt/strapi](https://strapi.nuxtjs.org/) module, no more GraphQL requests.
