### ISSUE TITLE
Cannot read property 'url' of undefined at fresh startup

### ISSUE THREAD

**Issue by JustinRvt** [strapi/strapi-starter-nuxt-blog#30]
Hello, fresh startup (because I'm struggling on a project and your tutorial that is not working at all for me after hour... days of work. Backend is running just fine, yet Frontend experiences this difficulty : 
I'm running node v12.9.0

It looks a lot like the issue i'm getting in my projects.

Thanks a lot!
```
 ERROR  [Vue warn]: Error in render: "TypeError: Cannot read property 'url' of undefined"                                                                                           17:18:04

found in

---> <ArticleCard> at components/ArticleCard.vue
       <Articles> at components/Articles.vue
         <Pages/index.vue> at pages/index.vue
           <Nuxt>
             <Layouts/default.vue> at layouts/default.vue
               <Root>
```

**Comment by remidej** [comment]
Hello! What were the instructions you were following? Were they the ones on the readme?

**Comment by JustinRvt** [comment]
Hi @remidej and thanks for your concern, 

I first used the "use this template" button, created a repo on my side and cloned it (yarn install, etc.)
Then I yarn created the backend with the --template option.

Only difference here is that I'm using Mongo and, for some reason, I also experience issues on other projects when my variables have more than 2 elements. For instance in ArticleCard.vue, it doesn't work with article.image.url or article.author.picture.url

**Comment by JustinRvt** [comment]
Well, it's working with SQLite. 

I think that Mongo is screwing up for some reason. Perhaps the same that made my app crashes.

**Comment by sukitfup** [comment]
With a mongodb installation look at your articles inside of strapi/admin. They're all missing. I just added my own images and it's working fine.

**Comment by remirobichet** [comment]
I also had the issue with a fresh install.
I figured out the problem came from my newly created 'writer'. I did not provide a picture for my writer (because the field wasn't required) and this thrown me an error from `ArticleCard.vue` (because there had no control over the `article.author.picture.url` data.

I don't know which solution is the best to fix this, add `"required": true` in `backend/api/writer/models/writer.settings.json`, or add a control on the `ArticleCard.vue` component.

**Comment by markkaylor** [comment]
> With a mongodb installation look at your articles inside of strapi/admin. They're all missing. I just added my own images and it's working fine.

@JustinRvt did this help you?

**Comment by ke11** [comment]
Those image assets(article.image.url) are not exist on ur production environment, so u get the error...

**Comment by markkaylor** [comment]
I believe this issue is related to https://github.com/strapi/strapi-template-blog/issues/5.  Closing this issue since we will address it there.
