### ISSUE TITLE
Request Display url from id to slug 

### ISSUE THREAD

**Issue by bdloner** [strapi/strapi-starter-nuxt-blog#5]
I still have a problem calling slug to show on url using apollo for a long time now, still can't solve. Can anyone help?

**Comment by eertmanhidde** [comment]
Sure, what do you exactly want to do? Can you maybe add some example code of what you've tried?

**Comment by swina** [comment]
Hi maybe I am late but in order to use friendy url (using slug) I suggest:

- have a slug field in the content

- create a graphql query articles-slug.gql in ./apollo/queries/article
Your new GraphQL query should be (add fields you need)

_./apollo/queries/article/articles-slugs.gql_

```
query Articles ( $slug : String){
  articles( where : { slug :$slug } ) {
    title 
    ...
}
```

- create a folder *_slug* in nuxt ./pages/article and then create a index.vue file 

*./pages/article/_slug/index.vue*
```

<template>
  ....
</template>

<script>
import articlesQuery from '~/apollo/queries/article/articles-slug'
export default {
   data:()=>({
      articles: {}
   }),
   apollo: {
    articles: {
      prefetch: true,
      query: articlesQuery,
      variables() {
        return { slug: this.$route.params.slug };
      },
      update: data => data.articles[0]
    }
  },
}
</script>
```

- change the nuxt-link in ./components/Articles.vue

```
<nuxt-link 
   v-for="article in articles" 
   :to="{ name: 'articles-slug', params: { slug : article.slug } }" :key="article.slug">
   {{ article.title }}
</nuxt-link>
```

**Comment by francisceril** [comment]
@swina I wanted the category to use slug as well, so `site.com/articles/news/` will list all articles under the news category. Could you guide me on how to achieve that please.
Thank you.

**Comment by swina** [comment]
As for articles create a `pages/categories/_slug/index` folder and create a `index.vue`

Your index.vue should look like
```
<template>
  ....
</template>

<script>
import categoryQuery from '~/apollo/queries/category/category-slug'
export default {
   data:()=>({
      categories: {}
   }),
   apollo: {
    categories: {
      prefetch: true,
      query: categoryQuery,
      variables() {
        return { slug: this.$route.params.slug }
      }
    }
  },
}
</script>
```
Your `category-slug.gql`

```
query Categorues ( $slug : String){
  categories( where : { slug :$slug } ) {
    title 
    ...
}
```

Your Categories collection needs to have a slug field in order to work.

**Comment by swina** [comment]
You will have a `categories/news` routing working available for a category news with slug news

**Comment by marvthedev** [comment]
For some reason when I added the image to the _slug.vue page, the article will not render the title and content.  Also when I go to other articles, I get an error: Cannot read property 'url' of undefined. The article page renders fine when I remove the image code.

```
<template>
  <article class="article">
    <div class="article__container">
      <h1 class="article__title">{{ articles.title }}</h1>
      <div class="article__img-container">
        <img :src="api_url + articles.image.url" class="article__img" />
      </div>
      <div
        class="article__content"
        v-html="$md.render(articles.content || 'No description provided')"
      ></div>
      <div class="article__side-bar"><p>Sidebar</p></div>
    </div>
  </article>
</template>

<script>
import articleQuery from "~/apollo/queries/article/Article";
export default {
  data() {
    return {
      api_url: process.env.strapiBaseUri,
    }
  },
  data: () => ({
    articles: {},
  }),
  apollo: {
    articles: {
      prefetch: true,
      query: articleQuery,
      variables() {
        return { slug: this.$route.params.slug };
      },
      update: data => data.articles[0]
    }
  }
};
</script>
```

**Comment by markkaylor** [comment]
Closing this issue since it seems @swina has answered the initial question and @marvthedev opened https://github.com/strapi/strapi-starter-nuxt-blog/issues/22
