### ISSUE TITLE
Why Nuxt Site is slow ??

### ISSUE THREAD

**Issue by mayank30** [strapi/strapi-starter-nuxt-blog#9]

**Comment by mayank30** [comment]
![image](https://user-images.githubusercontent.com/6511688/83979421-c27ed000-a92b-11ea-8e48-ebb669abad54.png)

Running code on local

**Comment by eertmanhidde** [comment]
hey man, change the `router-link`'s to `nuxt-link`'s. This fixed the issue for me at least. My fix is here: https://github.com/strapi/strapi-starter-nuxt-blog/pull/11

**Comment by mayank30** [comment]
Thanks for your reply I will give it a try

**Comment by Mcastres** [comment]
Thanks @eertmanhidde for this solution. I'm closing this for the moment :)
